command_timeout = 1000

[battery]
disabled = true

# Inserts a blank line between shell prompts
add_newline = true

[directory]
style = "bold bright-blue"

[git_branch]
style = "bold bright-red"

# Replace the ">" symbol in the prompt with "âœ"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[>](bold green)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count}"
behind = "ğŸ¢ Ã—${count}"
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
untracked = "ğŸ›¤ï¸  Ã—${count}"
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count}"
staged = "âœ”  Ã—${count}"
renamed = "ğŸ“› Ã—${count}"
deleted = "âœ˜  Ã—${count}"
style = "bright-white"
format = "$all_status$ahead_behind"

[git_commit]
only_detached = true
style = "bold black"
format = "[$hash]($style) "

[nodejs]
symbol = "ï¢˜ "

